---
# ###[ Restart timesyncd under Virtualbox ]######################################

- name: Restart timesyncd under Virtualbox Block
  when:
    - ansible_os_family == "Debian"
    - virtual_box|default(false)|bool
  tags:
    - install-zfs-packages
    - always
  block:
    # ZFS package installs have failed due to "not yet valid" message. This unusually happens
    # when time is not set correctly on the new system.  This happened often when virtualbox
    # snapshot images were used.  Restarting timesyncd service forces time to be updated.
    - name: Restarting timesync service under Virtualbox
      ansible.builtin.systemd:
        name: systemd-timesyncd
        state: restarted

    - name: Pause 10 seconds for time service to settle
      ansible.builtin.pause:
        seconds: 10

# ###[ Disable Auto-mounting ]###################################################
- name: Stop reused disks from being auto mounted
  tags:
    - install-zfs-packages
  block:
    - name: Stop reused disks from being auto mounted
      ansible.builtin.command: "gsettings set org.gnome.desktop.media-handling automount false"
      register: cmd_output
      changed_when: cmd_output.rc == 0

# ##[ Install Packages Need to get Started ]####################################
- name: Install Packages Need to get Started
  when: ansible_os_family == "Debian"
  tags:
    - install-zfs-packages
  block:
    - name: Install ZFS packages (assumes Live CD Environment)
      ansible.builtin.apt:
        name:
          - debootstrap
          - gdisk
          - zfs-initramfs
          - dosfstools
          - mdadm
          - software-properties-common
          - debconf-utils
        state: present
        update_cache: true
        cache_valid_time: 3600
        install_recommends: false

    - name: Stop ZED Service
      ansible.builtin.systemd:
        name: zed
        enabled: true
        state: stopped

###############################################################################
