---
# [ Install rEFInd Boot Manager ]##############################################
- name: Install rEFInd Boot Manager Block
  when:
    - ansible_nodename != "localhost"
  tags:
    - install_refind
  block:
    - name: Run chroot to mount EFI variables directory
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          EFIVARS_CNT=$(ls -1 {{ live_cd_mountpoint }}/{{ efi_firmware_vars_path }} | wc -l)
          if [ ${EFIVARS_CNT} -eq 0 ] ; then
            mount -t efivarfs efivarfs {{ live_cd_mountpoint }}/{{ efi_firmware_vars_path }}
          fi
      register: cmd_output
      changed_when: cmd_output.rc == 0

    - name: Run chroot command to mount /boot/efi directory
      ansible.builtin.command:
        cmd: "{{ chroot_cmd }} bash -c 'findmnt /boot/efi || mount {{ efi_boot_mountpoint }}'"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      args:
        creates: "{{ efi_boot_path }}"

    - name: Run chroot command to install rEFInd Boot Manager
      ansible.builtin.command:
        cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "DEBIAN_FRONTEND=noninteractive apt-get --yes install refind efi-shell-x64"
        - "refind-install --yes"
        - "mkdir -p {{ zfs_boot_menu_path }}"
        - "mkdir -p {{ refind_path }}"
      when:
        - ansible_os_family == "Debian"

    - name: Copy rEFInd template to /mnt/boot/efi/EFI/zfsbootmenu/refind_linux.conf
      ansible.builtin.template:
        src: refind_linux.conf.j2
        dest: "{{ live_cd_mountpoint }}{{ zfs_boot_menu_path }}/refind_linux.conf"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: Copy UEFI shell to EFI system
      ansible.builtin.copy:
        src: "{{ live_cd_mountpoint }}/usr/share/efi-shell-x64/shellx64.efi"
        dest: "{{ live_cd_mountpoint }}/boot/efi/EFI/tools/shellx64.efi"
        owner: "root"
        group: "root"
        mode: "0644"
        remote_src: true

    # If we're running under legacy bios then rEFInd will be installed
    # to /boot/efi/EFI/BOOT - we want it in /boot/efi/EFI/refind
    - name: Run chroot command to Move rEFInd if under Legacy BIOS
      ansible.builtin.command:
        cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "[ -e {{ efi_boot_path }}/BOOT ] &&
          mvrefind {{ efi_boot_path }}/BOOT {{ refind_path }} || true"

    - name: Reduce rEFIND boot menu timeout from 20 seconds to new value
      ansible.builtin.replace:
        path: "{{ live_cd_mountpoint }}{{ refind_path }}/refind.conf"
        regexp: '^timeout .*'
        replace: 'timeout {{ refind_boot_menu_timeout }}'

    - name: Copy Logo Images and Icons
      ansible.builtin.copy:
        src: "files/{{ item.source }}"
        dest: "{{ live_cd_mountpoint }}/{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: "0644"
      with_items:
        - { source: "{{ refind_boot_menu_logo_filename }}", dest: "{{ refind_path }}/{{ refind_boot_menu_logo_filename }}" }
        - { source: "os_linux.png", dest: "{{ refind_path }}/icons/"}
      when:
        - refind_boot_menu_logo  | default(false)

    - name: Enable banner_scale for Logo Images
      ansible.builtin.replace:
        path: "{{ live_cd_mountpoint }}{{ refind_path }}/refind.conf"
        regexp: '^#banner_scale (.*$)'
        replace: 'banner_scale \1'
      when:
        - refind_boot_menu_logo  | default(false)

    - name: Set Banner Logo Images
      ansible.builtin.replace:
        path: "{{ live_cd_mountpoint }}{{ refind_path }}/refind.conf"
        regexp: '^#banner hostname.bmp(.*$)'
        replace: 'banner {{ refind_boot_menu_logo_filename }}'
      when:
        - refind_boot_menu_logo  | default(false)

    - name: Add ZFSBootMenu configuration to end of refind.conf
      ansible.builtin.blockinfile:
        path: "{{ live_cd_mountpoint }}{{ refind_path }}/refind.conf"
        block: |
          # ZFSBootMenu EFI Loader Configuration
          menuentry "ZFSBootMenu" {
            loader EFI/zfsbootmenu/zfsbootmenu.efi
            icon EFI/refind/icons/os_ubuntu.png
          }
        insertafter: EOF

    - name: Copy startup script with multiple disks template to /mnt/boot/efi/startup.nsh
      ansible.builtin.template:
        src: startup.nsh.j2
        dest: "{{ live_cd_mountpoint }}{{ efi_boot_mountpoint }}/startup.nsh"
        owner: "root"
        group: "root"
        mode: "0644"
      when:
        - disk_by_id | length | int > 1

# [ Move rEFInd Boot Manager if EFI Fallback Enabled ]#########################
# Some BIOS hard code where the EFI boot manager is located, so we need to
# copy the rEFInd boot manager to the fallback location.
# This is usually /boot/efi/EFI/boot/bootx64.efi.
- name: Move rEFInd Boot Manager for EFI Fallback Block
  when:
    - ansible_nodename != "localhost"
  tags:
    - install_refind
    - efi_fallback_enabled | default(false) | bool
  block:
    - name: Create EFI fallback directory
      ansible.builtin.file:
        path: "{{ live_cd_mountpoint }}/{{ efi_boot_mountpoint }}/EFI/boot/"
        state: directory
        mode: "0755"

    - name: Run chroot command to Move rEFInd for EFI Fallback
      ansible.builtin.command:
        cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "[ -e {{ refind_path }} ] &&
          mvrefind {{ refind_path }} {{ efi_fallback_path }} || true"

    - name: Copy Logo Images and Icons to EFI Fallback
      ansible.builtin.copy:
        src: "files/{{ item.source }}"
        dest: "{{ live_cd_mountpoint }}/{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: "0644"
      with_items:
        - { source: "{{ refind_boot_menu_logo_filename }}", dest: "{{ efi_fallback_path }}/{{ refind_boot_menu_logo_filename }}" }
        - { source: "os_linux.png", dest: "{{ efi_fallback_path }}/icons/"}
      when:
        - refind_boot_menu_logo  | default(false)

    - name: Fix Logo Images for EFI Fallback
      ansible.builtin.replace:
        path: "{{ live_cd_mountpoint }}{{ efi_fallback_path }}/refind.conf"
        regexp: "EFI/refind/icons/"
        replace: "{{ efi_fallback_boot_path }}/icons/"

    - name: Copy Fallback startup script with multiple disks template to /mnt/boot/efi/startup.nsh
      ansible.builtin.template:
        src: startup-fallback.nsh.j2
        dest: "{{ live_cd_mountpoint }}{{ efi_boot_mountpoint }}/startup.nsh"
        owner: "root"
        group: "root"
        mode: "0644"
      when:
        - disk_by_id | length | int > 1
