---
# [ Create Regular / Non-root Users ]##########################################
- name: Create Regular User Block
  when:
    - ansible_nodename != "localhost"
  tags:
    - create_regular_users
  block:
    - name: Create ZFS data set for home directory of regular user
      community.general.zfs:
        name: "{{ root_pool_home_dataset_path }}/{{ item.user_id }}"
        state: present
        extra_zfs_properties:
          canmount: on # noqa yaml[truthy]
          mountpoint: "/home/{{ item.user_id }}"
      loop_control:
        label: "{{ item.user_id }}"
      loop: "{{ regular_user_accounts }}"
      register: home_dirs
      notify:
        - Create skeleton home directory structure

    - name: Create Regular User
      ansible.builtin.user:
        name: "{{ item.user_id }}"
        groups: "{{ item.groups }}"
        home: "/home/{{ item.user_id }}"
        password: "{{ item.password | password_hash('sha512') }}"
        update_password: on_create
        shell: "{{ item.shell }}"
        create_home: false
        state: present
      loop_control:
        label: "{{ item.user_id }}"
      loop: "{{ regular_user_accounts }}"
      register: accounts
      notify:
        - Force change password

    - name: Create Regular User .ssh directory
      ansible.builtin.file:
        state: directory
        owner: "{{ item.user_id }}"
        path: "/home/{{ item.user_id }}/.ssh"
        mode: "700"
      loop_control:
        label: "{{ item.user_id }}"
      loop: "{{ regular_user_accounts }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - create_regular_users

###############################################################################
