---
####################################################################################################
# This script is for installing and configuring ZFS on Root from an Ubuntu Live CD.
#
# Usage: --extra-vars='{"disk_devices": [sda, sdb], host_name: "mynewpc", passphrase: "mys3cret"}
#
# The "disk_devices" specifies the devices to erase all partitions from and install ZFS filesystem.
# The simple "sda" style references will be converted to "disk_by_id" references.
#
# If the required "disk_devices", or "host_name" is not specified, you will be prompted to enter it.
####################################################################################################

# [ Load up the secret files ]######################################################################
- name: Include Secret Files
  ansible.builtin.include_vars: "{{ item }}"
  tags: ["always"]
  loop:
    - secrets/main.yml
  no_log: "{{ no_log_secrets | default(true) }}"

- name: Include Task Files
  ansible.builtin.include_tasks: "{{ task_names }}"
  tags: ["always"]
  loop:
    - 01_test_virtualbox.yml
    - 01_basic_checks.yml
    - 01_test_secureboot.yml
    - 02_confirm_defaults.yml
    - 03_install_zfs_packages.yml
    - 04_clear_partition_tables.yml
    - 05_create_partitions.yml
    - 06_create_pools.yml
    - 07_create_filesystems.yml
    - 08_create_datasets.yml
    - 09_config_system.yml
    - 10_install_zfs.yml
    - 11_config_boot_filesystem.yml
    - 12_0-install_dracut.yml
    - 12_3-install_refind.yml
    - 12_4-install_syslinux.yml
    - 12_5-install_zfsbootmenu.yml
    - 12_6-config_swap.yml
    - 12_7-config_secureboot.yml
    - 13_system_tweaks.yml
    - 14_first_boot_prep.yml
    - 15_unmount_chroot.yml
    - 16_restart_remote.yml
    - 17_0-create_regular_user.yml
    - 17_1-install_google_auth.yml
    - 17_2-add_showip_service.yml
    - 17_5-copy_keys_notice.yml
    - 18_0-enable_dropbear.yml
    - 19_final_setup.yml
    - 20_restart_remote_final.yml
  loop_control:
    label: "{{ task_names }}"
    loop_var: task_names
