---
- name: "Create skeleton home directory structure"
  ansible.builtin.copy:
    src: "/etc/skel/."
    dest: "/home/{{ item.item.user_id }}"
    owner: "{{ item.item.user_id }}"
    group: "{{ item.item.user_id }}"
    mode: "0700"
    remote_src: true
  when: item.changed
  with_items: "{{ home_dirs.results }}"
  loop_control:
    label: "/home/{{ item.item.user_id }}"

- name: "Force change password"
  ansible.builtin.command:
    cmd: "chage -d 0 {{ item.item.user_id }}"
  when: item.changed
  register: cmd_output
  changed_when: cmd_output.rc == 0
  with_items: "{{ accounts.results }}"
  loop_control:
    label: "{{ item.item.user_id }}"

- name: Restart SSHD Server
  ansible.builtin.service:
    name: ssh
    state: restarted
  when: update_sshd.changed
